### ISSUE TITLE
Inconsistent use of function argument parameter

### ISSUE THREAD

**Issue by mattagape** [sbmlteam/deviser#12]
In `util/generateCode.py`, function `create_dir_structure()` takes a parameter `overwrite`. If this param is `False`, the function executes the line `print('directory already exists - terminating to avoid overwriting')`. BUT just before that, there is a call to `create_dir(directories[index], overwrite)`

If I look at create_dir(), it has the signature:
 `def create_dir(name, skip_existing):`

So the `skip_existing` parameter is the same as `overwrite`. But surely these want different outcomes to each other? Or have I missed something??

E.g. if `overwrite` is `True` (I want to overwrite any existing directory with this name), this means `skip_existing` will be True. So, if the directory already exists, the `create_dir()` function just skips it and says `done = True` … but it isn’t?!

**Comment by skeating** [comment]
I agree this is an incorrect use of arguments. We want to use 'overwrite' and if true things get overwritten, if false then they stay the same.
