### ISSUE TITLE
What should/does function ParseXML::to_bool return?

### ISSUE THREAD

**Issue by mattagape** [sbmlteam/deviser#15]
In `deviser/parseXML/ParseXML.py`, there is a function `to_bool()`. It is not clear what is/should be returned if  `v.lower()` is "false".

**Comment by fbergmann** [comment]
The intention was that the function returns `TRUE` for any of the strings "yes", "true", "1", and FALSE otherwise.

**Comment by mattagape** [comment]
Yes. Except that it only returns `False` if `v` is `None`. It doesn't appear to return **anything** if `v` is not `None` and `v.lower()` is `False`

**Comment by fbergmann** [comment]
But, in case if it is not one of the strings 'yes', 'true' or '1', then the expression `str in list` will return False, which is precisely what we want to have. 

    def to_bool(v):
            if v is None:
                return False
            return v.lower() in ("yes", "true", "1")
    
    
    In  : [ to_bool(x) for x in ['false', 'true', '0', '1', None, 'yes', 'no']]
    Out : [False, True, False, True, False, True, False]

**Comment by mattagape** [comment]
Yes, sorry @fbergmann you are absolutely correct!

**Comment by mattagape** [comment]
I'll add a comment to the function. This can be closed now.
