### ISSUE TITLE
Hard-coded magic numbers

### ISSUE THREAD

**Issue by mattagape** [sbmlteam/deviser#17]
In `ParseXML.py` function `parse_deviser.xml()`, the following lines appear:

        sbml_level = 3
        sbml_version = 1
        pkg_version = 1

We need to discuss what to do about these numbers. e.g. should they be stored in a "versions" file which Deviser reads in?

**Comment by skeating** [comment]
These numbers will always be the same so no real need to have a separate files. I'll close this but open again if you disagree.
