### ISSUE TITLE
Tests failing for run_cpp_tests.py

### ISSUE THREAD

**Issue by mattagape** [sbmlteam/deviser#40]
In `deviser/generator/tests/test_cpp_code`, `run_cpp_tests.py` experiences two test failures (for both Python 2 and Python 3):

```
REPORT for CPP Tests
All tests were run.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2 fails reported:
test-code/Def.h
test-code/Def.cpp
```

**Comment by skeating** [comment]
weirdly it passes for me with Python 3 !!

**Comment by mattagape** [comment]
Does it pass, or does it find that the files are missing, so it skips the test?
I found loads of these tests were failing because the paths to the files were wrong, so I had to update them.

**Comment by mattagape** [comment]
The problem seems to be that the reference files (`test-code/Def.h` and `test-code/Def.cpp`) have part of a licence file included, which the files generated by the tests do not have:

```
* This file is part of SOMETHING.
 * 

 * Copyright (C) 2013-2016 jointly by the following organizations:
 * 1. Abcdefg
 * 2. Hijklmonp
 *
```

The rest of the licence (and indeed the rest of the file) are the same for reference and test versions.

**Comment by mattagape** [comment]
It appears to be the content of `generator/tests/test_xml_files/copyright.txt`.

**Comment by skeating** [comment]
This is a test where the option to add a custom copyright has been set - so we would expect the generated files to have this copyright from the test folder.

It passes for me

**Comment by mattagape** [comment]
I just did this:
```
cd test_cpp_code
git checkout develop
git pull
python run_cpp_tests.py
...
...
****************************************************************
REPORT for CPP Tests
All tests were run.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2 fails reported:
test-code/Def.h
test-code/Def.cpp
****************************************************************
```

@skeating please can you run the test again, then scroll up to check that the tests have all passed, rather than being skipped over (as would happen with incorrect path)? Thanks.

**Comment by skeating** [comment]
So I clearly have a path problem:

Already on 'develop'
Your branch is up to date with 'origin/develop'.

(base) C:\Development\SBML\deviser\generator\tests\test_cpp_code>python run_cpp_tests.py
Traceback (most recent call last):
  File "run_cpp_tests.py", line 11, in <module>
    from tests import test_functions
ImportError: cannot import name 'test_functions' from 'tests' (C:\Users\Sarah\Anaconda3\lib\site-packages\tests\__init__.py)

But when I run within PyCharm all tests do pass

**Comment by skeating** [comment]
and using python install rather than conda I get:
====================================================
Testing copy:Def class with XMLNode
====================================================
Writing file Def.h
Writing file Def.cpp
temp\Def.h .... PASSED
temp\Def.cpp .... PASSED

...

****************************************************************
REPORT for CPP Tests
All tests were run.
No fails reported.
****************************************************************

**Comment by mattagape** [comment]
Interesting.

Outside of Conda, I still get the failures, with both Python 2 and Python3.

```
➜  test_cpp_code git:(develop) ✗ which python           
/usr/bin/python
➜  test_cpp_code git:(develop) ✗ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```
I'll try cloning the repo on the HPC and see what happens there

**Comment by mattagape** [comment]
OK, so for a clean install on the HPC, using Python 2, I still see these two failures.
```
2 fails reported:
test-code/Def.h
test-code/Def.cpp
****************************************************************
[cceagil@login12 test_cpp_code]$ which python
/usr/bin/python
```
It fails with python3 also.

```
[cceagil@login12 test_cpp_code]$ which python3
/shared/ucl/apps/python/bundles/python38-5.0.0/venv/bin/python3
[cceagil@login12 test_cpp_code]$ python3 --version
Python 3.8.6
[cceagil@login12 test_cpp_code]$ python3 run_cpp_tests.py 
====================================================
Testing copy:Def class with XMLNode
====================================================
Writing file Def.h
Writing file Def.cpp
temp/Def.h=================>> FAILED
temp/Def.cpp=================>> FAILED
```
is it possible you have a cached version of the relevant files?

**Comment by mattagape** [comment]
```
[cceagil@login12 test_cpp_code]$ diff temp/Def.h test-code/Def.h
29a30,36
>  * This file is part of SOMETHING.
>  * 
> 
>  * Copyright (C) 2013-2016 jointly by the following organizations:
>  * 1. Abcdefg
>  * 2. Hijklmonp
>  *
[cceagil@login12 test_cpp_code]$ diff temp/Def.cpp test-code/Def.cpp
29a30,36
>  * This file is part of SOMETHING.
>  * 
> 
>  * Copyright (C) 2013-2016 jointly by the following organizations:
>  * 1. Abcdefg
>  * 2. Hijklmonp
>  *
[cceagil@login12 test_cpp_code]$ 
[cceagil@login12 test_cpp_code]$ grep -n SOMETHING test-code/Def.h
30: * This file is part of SOMETHING.
[cceagil@login12 test_cpp_code]$ grep -n SOMETHING temp/Def.h
[cceagil@login12 test_cpp_code]$ 
```
So the test is failing to add in those few lines of licence file in these two cases.
I noticed I had commented out the test for Abc.h/.cpp. When I tried running it I got a xml.parsers.expat.ExpatError
But let's fix the Def.h/.cpp error first

**Comment by mattagape** [comment]
I think I might know the problem now.
The test for Def.h uses the XML file `deviser/generator/tests/test_xml_files/copy.xml`.
In that file we see this:
```
<package name="Copy" fullname="Copy Additional" number="100" offset="100000" version="1" required="false"
  additionalDecls="C:/Development/SBML/deviser/generator/tests/test_xml_files/ElementFilter.h" 
  additionalDefs="C:/Development/SBML/deviser/generator/tests/test_xml_files/ElementFilter.cpp" 
  customCopyright="C:/Development/SBML/deviser/generator/tests/test_xml_files/copyright.txt">
```
which assumes a Windows machine.
So it is failing on MacOS and Linux.
Similarly, Abc.h/.cpp uses XML file `copy_add.xml`, which also has Windows-specific information (looks identical to the above).
I guess we could use relative paths? Although that might stop it working when invoked from some directories?

**Comment by mattagape** [comment]
It didn't seem to like relative paths!
Hard-coding the path on the Myriad HPC made Def.h/.cpp work. (Haven't tried the other).
But obviously we want it platform-agnostic.

**Comment by skeating** [comment]
Ah - well spotted, the tests are hardcoded for my machine !

Bad Sarah.

I'll look at it next week
