### ISSUE TITLE
Deviser does not generate getAllElements

### ISSUE THREAD

**Issue by fbergmann** [sbmlteam/deviser#70]
It would seem that the getAllElements functions are not being generated. It would also be nice to have the ElementFilter functionality as we have it in libSBML automatically generated.

**Comment by skeating** [comment]
Are you talking for a package or for a.n.other library ?

**Comment by fbergmann** [comment]
a library, specifically in libSEDML i needed this functionality right now. But calling getAllElements returned 0, when it shouldn't. I was just wondering what to do to generate these functions, but ideally it'd be great if deviser would do it.
